version: "3.7"
services:
  uber-replica-db:
    image: postgres:13
    container_name: uber_replica_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_home:/var/lib/postgresql/data

  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8282:5000
    volumes:
      - ./backend/data:/data
    command: "osrm-routed --algorithm mld /data/vietnam-latest.osrm"
  # backend:
  #   image: uber_replica_db:1
  #   container_name: pygobe_app
  #   build:
  #     context: .
  #     args:
  #       - DOCKER_WORKDIR=${DOCKER_WORKDIR}
  #   ports:
  #     - "127.0.0.1:1234:1234"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  db_home:
    external: false
  grafana-data:
    external: true
