// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
	"time"
)

type Driver struct {
	ID           int64          `json:"id"`
	Phone        string         `json:"phone"`
	Name         sql.NullString `json:"name"`
	LoginCode    sql.NullString `json:"login_code"`
	Year         sql.NullInt32  `json:"year"`
	Make         sql.NullString `json:"make"`
	Model        sql.NullString `json:"model"`
	Color        sql.NullString `json:"color"`
	LicensePlate sql.NullString `json:"license_plate"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Engagement struct {
	ID         int64         `json:"id"`
	DriverID   int32         `json:"driver_id"`
	Status     int32         `json:"status"`
	InTrip     sql.NullInt32 `json:"in_trip"`
	Latitude   float64       `json:"latitude"`
	Longitude  float64       `json:"longitude"`
	GeofenceID int32         `json:"geofence_id"`
	CreatedAt  time.Time     `json:"created_at"`
}

type Trip struct {
	ID                      int64           `json:"id"`
	UserID                  int64           `json:"user_id"`
	DriverID                sql.NullInt32   `json:"driver_id"`
	ServiceType             int32           `json:"service_type"`
	IsStarted               bool            `json:"is_started"`
	DepartureLatitude       float64         `json:"departure_latitude"`
	DepartureLongitude      float64         `json:"departure_longitude"`
	DepartureName           string          `json:"departure_name"`
	DestinationLatitude     float64         `json:"destination_latitude"`
	DestinationLongitude    float64         `json:"destination_longitude"`
	DestinationName         string          `json:"destination_name"`
	DriverLocationLatitude  sql.NullFloat64 `json:"driver_location_latitude"`
	DriverLocationLongitude sql.NullFloat64 `json:"driver_location_longitude"`
	Fare                    sql.NullInt32   `json:"fare"`
	CreatedAt               time.Time       `json:"created_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      sql.NullString `json:"name"`
	Phone     string         `json:"phone"`
	LoginCode sql.NullString `json:"login_code"`
	CreatedAt time.Time      `json:"created_at"`
}
