// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: trip.sql

package db

import (
	"context"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    user_id,
    driver_id,
    origin_latitude,
    origin_longitude,
    destination_latitude,
    destination_longitude,
    destination_name
) VALUES (
    $1, NULL, $2, $3, $4, $5, $6
)
RETURNING id, user_id, driver_id, is_started, is_completed, origin_latitude, origin_longitude, destination_latitude, destination_longitude, destination_name, driver_location_latitude, driver_location_longitude, created_at
`

type CreateTripParams struct {
	UserID               int64   `json:"user_id"`
	OriginLatitude       float64 `json:"origin_latitude"`
	OriginLongitude      float64 `json:"origin_longitude"`
	DestinationLatitude  float64 `json:"destination_latitude"`
	DestinationLongitude float64 `json:"destination_longitude"`
	DestinationName      string  `json:"destination_name"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, createTrip,
		arg.UserID,
		arg.OriginLatitude,
		arg.OriginLongitude,
		arg.DestinationLatitude,
		arg.DestinationLongitude,
		arg.DestinationName,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DriverID,
		&i.IsStarted,
		&i.IsCompleted,
		&i.OriginLatitude,
		&i.OriginLongitude,
		&i.DestinationLatitude,
		&i.DestinationLongitude,
		&i.DestinationName,
		&i.DriverLocationLatitude,
		&i.DriverLocationLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec

DELETE FROM trips
WHERE id = $1
`

// -- name: UpdateTrip :one
// UPDATE users
// SET name = $2
// WHERE id = $1
// RETURNING *;
func (q *Queries) DeleteTrip(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, id)
	return err
}

const getTrip = `-- name: GetTrip :one
SELECT id, user_id, driver_id, is_started, is_completed, origin_latitude, origin_longitude, destination_latitude, destination_longitude, destination_name, driver_location_latitude, driver_location_longitude, created_at FROM trips
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTrip(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DriverID,
		&i.IsStarted,
		&i.IsCompleted,
		&i.OriginLatitude,
		&i.OriginLongitude,
		&i.DestinationLatitude,
		&i.DestinationLongitude,
		&i.DestinationName,
		&i.DriverLocationLatitude,
		&i.DriverLocationLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const listTrips = `-- name: ListTrips :many
SELECT id, user_id, driver_id, is_started, is_completed, origin_latitude, origin_longitude, destination_latitude, destination_longitude, destination_name, driver_location_latitude, driver_location_longitude, created_at FROM trips
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTripsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrips(ctx context.Context, arg ListTripsParams) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTrips, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DriverID,
			&i.IsStarted,
			&i.IsCompleted,
			&i.OriginLatitude,
			&i.OriginLongitude,
			&i.DestinationLatitude,
			&i.DestinationLongitude,
			&i.DestinationName,
			&i.DriverLocationLatitude,
			&i.DriverLocationLongitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
